# https://taskfile.dev/#/
version: "3"

vars:
  PYTHON: python3
env:
  FLIT_ROOT_INSTALL: "1"

tasks:
  install:base:
    status:
      - test -f .venvs/base/bin/flitenv
    cmds:
      - "{{.PYTHON}} -m venv .venvs/base"
      - .venvs/base/bin/python3 -m pip install -U flit
      - .venvs/base/bin/flit install --symlink --deps=production
  install:test:
    sources:
      - pyproject.toml
    status:
      - test -f .venvs/test/bin/pytest
    deps:
      - install:base
    cmds:
      - .venvs/base/bin/python3 -m flitenv test install
  pytest:run:
    desc: "run Python tests"
    deps:
      - install:test
    cmds:
      - .venvs/base/bin/python3 -m flitenv test run pytest {{.CLI_ARGS}}

  release:
    desc: generate and upload a new release
    deps:
      - install:base
    cmds:
      - which gh
      - test {{.CLI_ARGS}}
      - cat flitenv/__init__.py | grep {{.CLI_ARGS}}
      - rm -rf dist/
      - .venvs/base/bin/flit build
      - .venvs/base/bin/flit publish
      - git tag {{.CLI_ARGS}}
      - git push
      - git push --tags
      - gh release create --generate-notes {{.CLI_ARGS}}
      - gh release upload {{.CLI_ARGS}} ./dist/*
